version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: karma-sauce-launcher
    versions:
    - 4.3.6
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.8
  - dependency-name: rollup
    versions:
    - 2.41.2
    - 2.42.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.17
    - 7.13.10
  - dependency-name: karma-typescript
    versions:
    - 5.5.0
  - dependency-name: karma
    versions:
    - 6.2.0
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: puppeteer
    versions:
    - 7.0.1
    - 7.1.0
    - 8.0.0
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.0.0
    - 17.1.0
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.0
  registries:
  - npm-registry-registry-npmjs-org
