# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test_build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run build

workflows:
  version: 2
  push:
    jobs:
      - test_build
  scheduled:
    jobs:
      - test_build
    triggers:
      - schedule:
          cron: "55 8 * * *"
          filters:
            branches:
              only:
                - master
